### ISSUE TITLE
PAT error whn trying to activate the plugin

### ISSUE THREAD

**Issue by FredericFournier** [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin#71]
Hi

I get this error when I try to activate the plugin.

Thank you for your help

![PAT_error](https://github.com/user-attachments/assets/9306ac88-d6cd-4db2-bc91-dd8f83cb9310)

**Comment by cratcliff** [comment]
@FredericFournier I have just released a new version. Can you install it and let me know if this fixes your issue?

**Comment by jonasko-qgz** [comment]
@cratcliff The problem still exist after updating the plugin to 1.10. 


2025-03-01T07:50:54     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib\site-packages\pyprecag\__init__.py", line 65, in 
              proj_lib = pyproj.datadir.pyproj_datadir
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: module 'pyproj.datadir' has no attribute 'pyproj_datadir'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/julia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\__init__.py", line 156, in classFactory
              _ = plugin_status(level='basic', check_for_updates=check_online)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/julia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\util\check_dependencies.py", line 434, in plugin_status
              df_py[['package', 'current', 'available', 'file', 'source']] = df_py['name'].apply(check_python_dependencies,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib\site-packages\pandas\core\series.py", line 4924, in apply
              ).apply()
              ^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib\site-packages\pandas\core\apply.py", line 1427, in apply
              return self.apply_standard()
              ^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib\site-packages\pandas\core\apply.py", line 1507, in apply_standard
              mapped = obj._map_values(
              ^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib\site-packages\pandas\core\base.py", line 921, in _map_values
              return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib\site-packages\pandas\core\algorithms.py", line 1743, in map_array
              return lib.map_infer(values, mapper, convert=convert)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "lib.pyx", line 2972, in pandas._libs.lib.map_infer
              File "C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib\site-packages\pandas\core\apply.py", line 1496, in curried
              return func(x, *self.args, **self.kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/julia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\util\check_dependencies.py", line 250, in check_python_dependencies
              exec(f'import {package_name}')
              File "", line 1, in 
              File "C:\PROGRA~1/QGIS33~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib\site-packages\pyprecag\__init__.py", line 73, in 
              assert os.path.isfile(
              ^^^^^^^^^^^^^^^
             AssertionError: Could not find PROJ_LIB directory

**Comment by cratcliff** [comment]
@jonasko-qgz What version of QGIS are you using?
Can you try uninstalling the plugin, upgrade to the most recent release ( QGIS 3.42 or LTR 3.40) and installing again?
